name: Deploy site to Google

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
defaults:
  run:
    shell: bash

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
    # - id: 'upload-folder'
    #   uses: 'google-github-actions/upload-cloud-storage@v2'
    #   with:
    #     path: 'public'
    #     destination: ${{ vars.BUCKET_NAME }}
    #     parent: false
    - name: 'Sync Folder'
      run: gsutil -m rsync -r -c -d public gs://${{ vars.BUCKET_NAME }}
