name: "Apply Terraform Changes"

on:
  workflow_dispatch: {}

permissions: 
  id-token: write
  contents: read

jobs:
  apply:
    name: Terraform Apply
    uses: tangental-io/terraform/.github/workflows/terraform-apply-template.yml@main
    with:
      working_directory: ${{ vars.TF_WORKING_DIRECTORY }}